### ISSUE TITLE
 Cannot detect correct region from bucket 

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/OhdsiSharing#2]
When using submitResults i get the following message:
 
Error in get_region.default(bucket, key = key, secret = secret, session_token = session_token) : 
  Cannot detect correct region from bucket 

There seem to be some known issues with aws.s3?:
https://github.com/cloudyr/aws.s3/issues/106

**Comment by msuchard** [comment]
@PRijnbeek - do you think if I added a `region` parameter (defaulted to the correct region) to `submitResults()` all will work well?

**Comment by PRijnbeek** [comment]
I tried this:
    result <- OhdsiSharing::putS3File(file = zipName,
                                      bucket = "ohdsi-study-plp",
                                      key = key,
                                      secret = secret,
                                      region = "us-east-1")

but still the same problem. 

By the way it is already default in the putS3File function:
OhdsiSharing::putS3File
function (file, bucket, region = "us-east-1", key, secret, appendUuid = TRUE)

**Comment by schuemie** [comment]
It seems the aws.s3 package has some different behavior than before. I just made some modifications that solve the problem on my end (I can push files, but I don't know whether they actually arrive). 

Could you reinstall the package and try again?

**Comment by PRijnbeek** [comment]
Checked and works fine now, i also see your uploaded files in the bucket.

Thanks.
