### ISSUE TITLE
Test tag / deploy behavior

### ISSUE THREAD

**Issue by msuchard** [OHDSI/OhdsiSharing#3]
- [x] correctly compares versions
- [ ] correctly makes tag
- [x] correctly deploys to `drat` and `docker`
- [ ] already to deploy to other packages

@schuemie -- what was your recent experience?

**Comment by schuemie** [comment]
I now have it running for CohortMethod. The tagging seems to work well. I think we're ready to roll it out to the rest of the Methods Library.
