### ISSUE TITLE
Add sftp tests

### ISSUE THREAD

**Issue by ablack3** [OHDSI/OhdsiSharing#5]
Hi @leeevans and @schuemie,
Is there a folder on the OHDSI SFTP server that I can use to test this package? I'm guessing I might need a private key file on the github actions server too. Looking for some guidance on how to test the functions in [Sftp.R](https://github.com/OHDSI/OhdsiSharing/blob/master/R/Sftp.R)

**Comment by leeevans** [comment]
SFTP user was added as a secret for unit testing. Thanks @jreps for adding the sftp unit tests in the HADES test-a-thon!
